# Generated by Django 5.2.7 on 2025-12-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='answers',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='quest',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
